<?php

namespace GalleryBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getGalleriesPaginator($page = null, $nbPerPage = null)
    {
        $query = $this->createQueryBuilder("gallery")
                ->leftjoin("gallery.photos", "photo")
                ->addSelect("photo")
                ->orderBy("gallery.date", "DESC")
        ;

        if (!is_null($page) && !is_null($nbPerPage))
            $query
                    ->setFirstResult(($page - 1) * $nbPerPage)
                    ->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }

    public function getGalleryDetail($id)
    {
        return $this->createQueryBuilder("gallery")
                        ->leftjoin("gallery.photos", "photo")
                        ->addSelect("photo")
                        ->where("gallery.id = :id")
                        ->setParameter("id", $id)
                        ->orderBy("photo.id", "ASC")
                        ->getQuery()
                        ->getSingleResult()
        ;
    }

    public function getActiveGalleries()
    {
        return $this->createQueryBuilder("gallery")
                        ->join("gallery.photos", "photo")
                        ->addSelect("photo")
                        ->where('gallery.active = :active')
                        ->setParameter('active', true)
                        ->orderBy("gallery.date", "ASC")
                        ->addOrderBy("photo.id", "ASC")
                        ->getQuery()
                        ->getResult()
        ;
    }

}
