<?php

namespace GalleryBundle\Repository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrderPhotos($order_id)
    {
        return $this->createQueryBuilder('photo')
            ->leftjoin('photo.details', 'detail')
            ->where('detail.order = :order_id')
            ->setParameter('order_id', $order_id)
            ->getQuery()
            ->getResult();
    }
}
