imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@GalleryBundle/Resources/config/services.yml" }
    - { resource: "@CartBundle/Resources/config/services.yml" }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_config: '@app_config'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.6
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: '%kernel.cache_dir%/swiftmailer/spool'

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            softdeleteable: true

vich_uploader:
    db_driver: orm
    mappings:
        gallery_photos:
            uri_prefix:         /gallery/photos
            upload_destination: '%kernel.root_dir%/../web/gallery/photos'
            namer:              vich_uploader.namer_uniqid

stfalcon_tinymce:
    language: %locale%
    theme:
        # Simple theme: same as default theme
        simple:
            height: 500
            plugins:
                - "advlist autolink autosave lists link image charmap print preview hr"
                - "searchreplace wordcount visualblocks visualchars code"
                - "insertdatetime media save table contextmenu directionality"
                - "emoticons paste textcolor"
            toolbar1: "undo redo | styleselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media emoticons | print preview"
            autosave_interval: "20s"
            autosave_ask_before_unload: true
            autosave_restore_when_empty: true
            autosave_retention: "20m"

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        gallery_thumb:
            quality: 80
            filters:
                relative_resize:
                  widen: 255
        watermark_thumb:
            quality: 80
            filters:
                relative_resize:
                    heighten: 800
                watermark:
                    image: Resources/data/watermark.png
                    size: 0.8
                    position: center
        slideshow_thumb:
            quality: 80
            filters:
                relative_resize:
                  heighten: 800
