homeredirect:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home
        permanent: true

adminredirect:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: gallery_index
        permanent: true

frontend:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/app
    requirements:
        _locale: en|fr

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/cart
    requirements:
        _locale: en|fr

gallery:
    resource: "@GalleryBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/gallery
    requirements:
        _locale: en|fr

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"