<?php

namespace CartBundle\Repository;

/**
 * CartQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartQuantityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQuantityLine($user, $photo, $format)
    {
        return $this->createQueryBuilder('quantity')
                ->join('quantity.cart', 'cart')
                ->where('cart.user = :user')
                ->andWhere('cart.photo = :photo')
                ->andWhere('quantity.format = :format')
                ->setParameters(array(
                    'user' => $user,
                    'photo' => $photo,
                    'format' => $format
                ))
                ->getQuery()
                ->getOneOrNullResult()
                ;
    }
}
