<?php

namespace CartBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCartFormat($user)
    {
        return $this->createQueryBuilder('cart')
                        ->join('cart.quantities', 'quantity')
                        ->addSelect('quantity')
                        ->join('quantity.format', 'format')
                        ->addSelect('format')
                        ->where('cart.user = :user')
                        ->setParameter("user", $user)
                        ->getQuery()
                        ->getResult()
        ;
    }

    public function getCartForOrder($user)
    {
        return $this->createQueryBuilder('cart')
                        ->join('cart.quantities', 'quantity')
                        ->addSelect('quantity')
                        ->join('quantity.format', 'format')
                        ->addSelect('format')
                        ->join('cart.photo', 'photo')
                        ->addSelect('photo')
                        ->join('photo.gallery', 'gallery')
                        ->addSelect('gallery')
                        ->where('cart.user = :user')
                        ->andWhere('quantity.quantity > :quantity')
                        ->setParameter("user", $user)
                        ->setParameter("quantity", 0)
                        ->getQuery()
                        ->getResult()
        ;
    }
}
