<?php

namespace CartBundle\Repository;

/**
 * DetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDetailPhotoUser($id)
    {
        return $this->createQueryBuilder('detail')
            ->join('detail.order', 'orderheader')
            ->addSelect('orderheader')
            ->join('orderheader.user', 'user')
            ->addSelect('user')
            ->join('detail.photo', 'photo')
            ->addSelect('photo')
            ->where('detail.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
