<?php

namespace CartBundle\Repository;

/**
 * OrderQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderQuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
